In [1]:
import numpy as np

In [2]:
x = np.array([0,1,2,3])

In [3]:
x

array([0, 1, 2, 3])

In [4]:
y = np.array([2,3,4,5])

In [5]:
y

array([2, 3, 4, 5])

In [6]:
x + 1

array([1, 2, 3, 4])

In [7]:
x*x

array([0, 1, 4, 9])

In [8]:
x * y

array([ 0,  3,  8, 15])

In [9]:
x.sum()

6

In [10]:
y.sum()

14

In [11]:
y.T

array([2, 3, 4, 5])