In [17]:
import numpy as np

In [18]:
my_list = [-17,0,4,5,9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [19]:
my_array_from_list * 10

array([-170,    0,   40,   50,   90])

In [20]:
my_array_from_list + 1

array([-16,   1,   5,   6,  10])